In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import math
import sys
import random

In [6]:
s = 'flu_data.csv'
df = pd.read_csv(s)
key=['Risk','NoFaceContact','Sick','HndWshFreq']
d=pd.DataFrame(df[key])
d['Sick'].fillna(value=np.mean(d['Sick']),inplace=True)

In [11]:
def hardfuzzy(d,k,m,maxiter):
    error=100
    data=np.array(d)
    n,m=data.shape
    centers=[[] for i in range(k)]
    membership=[]
    clusters=[[] for i in range(k)]
    cent=[[] for i in range(k)]
    distances=[[[] for j in range(k)] for i in range(n)]
    for i in range(n):
        x =random.randint(0,1)
        y=random.randint(0, 1-x)
        z=random.randint(0,1-x-y)
        v=1-x-y-z
        membership.append([x,y,z,v])
    for j in range(k):
            num=0
            den=0
            for i in range(n):
                num=num+(math.pow(membership[i][j],m)*data[i])
                den=den+(math.pow(membership[i][j],m))
            centers[j]=num/den  
    cent=centers        
    for ite in range(maxiter):
        if(error < 0.000000001):
            break
        for i in range(n):
            for j in range(k):
                distances[i][j]=math.sqrt(((centers[j][0]-data[i,0])*(centers[j][0]-data[i,0]))+((centers[j][1]-data[i,1])*(centers[j][1]-data[i,1]))+((centers[j][2]-data[i,2])*(centers[j][2]-data[i,2]))+((centers[j][3]-data[i,3])*(centers[j][3]-data[i,3])))
                if(distances[i][j]==0):
                    distances[i][j]=0.001
            dc=distances[i]        
            clusters[dc.index(min(dc))].append([data[i,0],data[i,1],data[i,2],data[i,3]])        
        for i in range(n):
            for j in range(k):
                p=0
                for f in range(k):
                    p=p+((math.pow(distances[i][j],(2/(m-1))))/(math.pow(distances[i][f],(2/(m-1))))) 
                membership[i][j]=round(1/p,3)       
        for j in range(k):
            num=0
            den=0
            for i in range(n):
                num=num+(math.pow(membership[i][j],m)*data[i])
                den=den+(math.pow(membership[i][j],m))
            centers[j]=num/den   
        su=0    
        for i in range(k): 
            su=su+math.dist(centers[i],cent[i])    
        cent=centers
        error=su/k
    mn = sys.maxsize
    for i in range(k):
        for j in range(i+1,k):
            for h in range(len(clusters[i])):
                for l in range(len(clusters[j])):
                    dist=math.dist(data[i],data[j])
                    if(dist < mn):
                        mn=dist        
    mx=0           
    for g in range(k):
        for i in range(len(clusters[g])):
            for j in range(i+1,len(clusters[g])):
                dist=math.dist(clusters[g][i],clusters[g][j])
                if(dist > mx):
                    mx=dist 
    index=mn/mx
    print(index)
    for g in centers:
        print(g)    
hardfuzzy(d,3,2,20)        

0.1811294732816565
[-0.08943841  2.50271796  1.00198028  3.25181485]
[-0.09876108  2.36473038  0.97580018  3.09277382]
[-0.12381104  2.49839085  0.98268159  3.34623524]
