In [5]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import math
import sys
import random

In [6]:
s = 'flu_data.csv'
df = pd.read_csv(s)
key=['Risk','NoFaceContact','Sick','HndWshFreq','HndWshQual']
d=pd.DataFrame(df[key])
d['Sick'].fillna(value=np.mean(d['Sick']),inplace=True)

In [9]:
def fuzzy5(d,k,m,maxiter):
    error=100
    data=np.array(d)
    n,m=data.shape
    centers=[[] for i in range(k)]
    membership=[]
    cent=[[] for i in range(k)]
    distances=[[[] for j in range(k)] for i in range(n)]
    for i in range(n):
        x =round(random.uniform(0.001,1),3)
        y=round(random.uniform(0.001, 1-x),3)
        z=round(random.uniform(0.001,1-x-y),3)
        u=round(random.uniform(0.001,1-x-y-z),3)
        v=round(1-x-y-z-u,3)
        membership.append([x,y,z,u,v])
    for j in range(k):
            num=0
            den=0
            for i in range(n):
                num=num+(math.pow(membership[i][j],m)*data[i])
                den=den+(math.pow(membership[i][j],m))
            centers[j]=num/den  
    cent=centers        
    for ite in range(maxiter):
        if(error < 0.00000001):
            break
        for i in range(n):
            for j in range(k):
                distances[i][j]=math.sqrt(((centers[j][0]-data[i,0])*(centers[j][0]-data[i,0]))+((centers[j][1]-data[i,1])*(centers[j][1]-data[i,1]))+((centers[j][2]-data[i,2])*(centers[j][2]-data[i,2]))+((centers[j][3]-data[i,3])*(centers[j][3]-data[i,3]))+((centers[j][4]-data[i,4])*(centers[j][4]-data[i,4])))
                if(distances[i][j]==0):
                    distances[i][j]=0.001
        for i in range(n):
            for j in range(k):
                p=0
                for f in range(k):
                    p=p+((math.pow(distances[i][j],(2/(m-1))))/(math.pow(distances[i][f],(2/(m-1))))) 
                membership[i][j]=round(1/p,3)       
        for j in range(k):
            num=0
            den=0
            for i in range(n):
                num=num+(math.pow(membership[i][j],m)*data[i])
                den=den+(math.pow(membership[i][j],m))
            centers[j]=num/den   
        su=0    
        for i in range(k): 
            su=su+math.dist(centers[i],cent[i])    
        cent=centers
        error=su/k    
    for g in centers:
        print(g)    
fuzzy5(d,3,2,20)

[-0.09946142  2.71626805  1.01132136  3.21505771  3.92756132]
[-0.10405003  2.42945493  0.97609835  3.28130957  3.92386345]
[-0.11235004  2.2205729   0.97338079  3.17952724  3.80553202]
